Fix/dockerfile
ufcg-lsd/saps-scheduler pull request #4
Opened 2020-07-06 13:58 UTC by wesleymonte

2020-07-06 19:01 UTC, raonismaneoto requested changes

2020-07-06 19:01 UTC, raonismaneoto commented on pom.xml
> +		<repository>
what is it?

2020-07-06 19:35 UTC, wesleymonte commented on pom.xml
> +		<repository>
Description of a local repository (directory) for maven searches for dependencies. I added this for use in building the docker image.

2020-07-06 21:12 UTC, thiagoyeds approved these changes

2020-07-08 17:39 UTC, raonismaneoto approved these changes

2020-10-29 20:52 UTC, thiagomanel approved these changes
lgtm

2020-10-29 20:52 UTC, merged